[agent]
name = "genai-recipe-agent"
version = "0.0.1"

[options.OPENAI_API_KEY]
type = "string"
description = "API key for OpenAI (used by the agent when online)"

[options.NOTION_API_TOKEN]
type = "string"
description = "Notion API token for Best Practice repository"

[options.NOTION_BEST_PRACTICES_DB_ID]
type = "string"
description = "Notion database ID for Best Practices"

[options.TIMEOUT_MS]
type = "string"
description = "Connection/tool timeouts in ms"
default = "300"

[runtimes.executable]
command = ["bash", "-c", "./run_agent.sh main.ts"]


